### ISSUE TITLE
A really awesome feature

### ISSUE THREAD

**Issue by anwaraltamimi** [anwaraltamimi/new-repo#2]
A description

#Todo
- [ ] set up a backend
- [ ] write an api
- [ ] do some frontend
